from turtle import *
from math import sqrt
print('programa para visualizar un segmento y su longitud')
x1=float(input('introduzca valor de x1: '))
y1=float(input('introduzca valor de y1: '))
x2=float(input('introduzca valor de x2: '))
y2=float(input('introduzca valor de y2: '))
pantalla=Screen()
pantalla.setup(800,600)
pantalla.screensize(900,700)
tortuga=Turtle()
penup()
goto(x1,y1)
pendown()
goto(x2,y2)
L=sqrt((x2-x1)**2+(y2-y1)**2)
penup()
goto(-(x1+x2)/2,-(y1+y2)/2)
pendown()
write('la longitud del segmento es {0:.2f}'.format(L))
pantalla.exitonclick()